# Dapr Secret Store Component: Kubernetes Secrets
# Provides secure access to Kubernetes secrets for application
#
# This component allows Dapr applications to retrieve secrets from
# Kubernetes native secret store without direct Kubernetes API access
#
# Prerequisites:
# - Kubernetes secrets created (./scripts/setup-secrets.sh)
#
# Documentation:
# - Dapr Kubernetes Secrets: https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []

---

# Example: How to reference secrets in other Dapr components
#
# In any Dapr component (pubsub, state, bindings, etc.), you can reference
# Kubernetes secrets using secretKeyRef:
#
# metadata:
# - name: connectionString
#   secretKeyRef:
#     name: database-credentials  # Kubernetes secret name
#     key: connection-string      # Key within the secret
#
# This prevents hardcoding sensitive values in component configurations

---

# Alternative: Azure Key Vault Secret Store (Future Enhancement)
# For enhanced security and centralized secret management
# Uncomment and configure for production deployment

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: azurekeyvault-secrets
#   namespace: default
# spec:
#   type: secretstores.azure.keyvault
#   version: v1
#   metadata:
#   - name: vaultName
#     value: "hackathon-todo-kv"
#   - name: azureTenantId
#     value: "your-tenant-id"
#   - name: azureClientId
#     value: "your-client-id"
#   - name: azureClientSecret
#     secretKeyRef:
#       name: azure-credentials
#       key: client-secret
