"""Add conversations and messages tables for chat endpoint

Revision ID: 3451e5a5cdef
Revises: b9c2d3e4f5f6
Create Date: 2026-01-30 11:56:23.093684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3451e5a5cdef'
down_revision: Union[str, Sequence[str], None] = 'b9c2d3e4f5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_table('account')
    op.drop_table('session')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('verification')
    op.alter_column('focus_sessions', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('focus_sessions_task_id_fkey'), 'focus_sessions', type_='foreignkey')
    op.drop_constraint(op.f('focus_sessions_user_id_fkey'), 'focus_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'focus_sessions', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'focus_sessions', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(op.f('uq_user_tag_name'), 'tags', type_='unique')
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_task_completions_user_date'), table_name='task_completions')
    op.drop_constraint(op.f('task_completions_task_id_fkey'), 'task_completions', type_='foreignkey')
    op.drop_constraint(op.f('task_completions_user_id_fkey'), 'task_completions', type_='foreignkey')
    op.create_foreign_key(None, 'task_completions', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'task_completions', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('task_tags_tag_id_fkey'), 'task_tags', type_='foreignkey')
    op.drop_constraint(op.f('task_tags_task_id_fkey'), 'task_tags', type_='foreignkey')
    op.create_foreign_key(None, 'task_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'task_tags', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('user', 'image',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.create_foreign_key(op.f('task_tags_task_id_fkey'), 'task_tags', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_tags_tag_id_fkey'), 'task_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.create_foreign_key(op.f('task_completions_user_id_fkey'), 'task_completions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_completions_task_id_fkey'), 'task_completions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_task_completions_user_date'), 'task_completions', ['user_id', 'completed_at'], unique=False)
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_tag_name'), 'tags', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'focus_sessions', type_='foreignkey')
    op.drop_constraint(None, 'focus_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('focus_sessions_user_id_fkey'), 'focus_sessions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('focus_sessions_task_id_fkey'), 'focus_sessions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('focus_sessions', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('verification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('emailVerified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('session_userId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey')),
    sa.UniqueConstraint('token', name=op.f('session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('account',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accessToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('account_userId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey')),
    sa.UniqueConstraint('providerId', 'accountId', name=op.f('account_providerId_accountId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
