#!/bin/bash
# Quick deployment script for Minikube
# Generated by phase4-k8s-blueprint skill

set -e

echo "🚀 Deploying to Minikube..."

# Configure Docker to use Minikube
eval $(minikube docker-env)

# Build images
echo "📦 Building Docker images..."
docker build -t todo-backend:latest -f backend/Dockerfile backend/
docker build -t todo-frontend:latest -f frontend/Dockerfile frontend/

# Deploy with Helm
echo "🎯 Deploying with Helm..."
helm upgrade --install todo-chatbot ./helm/todo-chatbot \
  --namespace todo-chatbot \
  --create-namespace \
  --wait

echo "✅ Deployment complete!"
echo "Access: minikube service todo-chatbot-frontend -n todo-chatbot"
